name: terraform
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_version: latest
      TF_working_dir: './terraform/'
      TF_VAR_linode_api_token: ${{ secrets.LINODE_API_TOKEN }}
      TF_VAR_linode_public_ssh_key: ${{ secrets.LINODE_PUBLIC_SSH_KEY }}
    steps:
      - name: env TF_VAR_linode_instance_label
        run: echo ::set-env name=TF_VAR_linode_instance_label::${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}
      - name: checkout
        uses: actions/checkout@master
      - name: terraform fmt
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: fmt
      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: init
      - name: terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: validate
      - name: terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: plan